

cache:
  key: "$CI_BUILD_NAME"
  untracked: true

image: anasdox/phpwebbuilder:latest

stages:
  - build
  - quality-gates
  - unit-test
  - package
  - deploy
  - integration-test
  - fonctional-test

build:
  stage: build
  script:
    - ./automation/bin/build.sh
  artifacts:
    paths:
    - .
    expire_in: 1 week

code-sniffer:
  stage: quality-gates
  dependencies:
    - build
  script:
    - ./automation/bin/code_sniffer.sh

#unit-test:
#  stage: unit-test
#  dependencies:
#    - build
#  script:
#    - ./automation/bin/unit-test.sh

deploy-integ:
  stage: deploy
  dependencies:
    - build
  environment:
    name: CI
    url: http://${CI_PROJECT_NAME}.ci.dalkia.niji.delivery
  only:
    - master
  tags:
#    - CI
#  script:
#    - docker-compose build
#    - docker-compose up -d
#    - docker-compose restart#
