cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .

image: anasdox/phpwebbuilder:latest

stages:
  - build
  - quality-gates
  - package
  - deploy

variables:
  CI_DEBUG_TRACE: "true"

build:
  stage: build
  script:

    - ./automation/bin/build.sh
  tags:
    - build

code-sniffer:
  stage: quality-gates
  variables:
    GIT_STRATEGY: none
  dependencies:
    - build
  script:
    - ls -ltra
    - ./automation/bin/code_sniffer.sh
  tags:
    - build

publish-artifact:
  stage: package
  dependencies:
    - build
  script:
    - tar --exclude-vcs --exclude='composer.*' --exclude='docker*.yml' --exclude='setup-dev*' --exclude='*.md' -zcf /tmp/${CI_COMMIT_REF_NAME}.tar.gz *
    - "curl -H\"Authorization: Bearer ${ARTIFACTORY_ACCESS_TOKEN}\" -T /tmp/${CI_COMMIT_REF_NAME}.tar.gz https://artifactory.niji.delivery/artifactory/niji-socle-drupal-local/${CI_COMMIT_REF_NAME}.tar.gz -k"
  tags:
    - build

deploy-dev:
  stage: deploy
  variables:
    APP_DOMAIN: '${CI_PROJECT_PATH_SLUG}.dev.${BASE_DOMAIN}'
    COMPOSE_PROJECT_NAME: '${CI_PROJECT_PATH_SLUG}_dev'
  script:
    - "echo \"Deploy to : ${APP_DOMAIN}\""
    - source /etc/.env && docker-compose up -d
  when: manual
  dependencies:
    - build
  environment:
    name: integ
    url: http://${CI_PROJECT_PATH_SLUG}.dev.${BASE_DOMAIN}
  only:
    - master
  tags:
    - dev

deploy-integ:
  stage: deploy
  variables:
    APP_DOMAIN: ${CI_PROJECT_PATH_SLUG}.integ.${BASE_DOMAIN}
    COMPOSE_PROJECT_NAME: '${CI_PROJECT_PATH_SLUG}_integ'
  script:
    - "echo \"Deploy to : ${APP_DOMAIN}\""
    - source /etc/.env && docker-compose up -d
  dependencies:
    - build
  environment:
    name: integ
    url: http://${CI_PROJECT_PATH_SLUG}.integ.${BASE_DOMAIN}
  only:
    - master
  tags:
    - integ

deploy-rec:
  stage: deploy
  variables:
    APP_DOMAIN: ${CI_PROJECT_PATH_SLUG}.rec.${BASE_DOMAIN}
    COMPOSE_PROJECT_NAME: '${CI_PROJECT_PATH_SLUG}_rec'
  script:
    - "echo \"Deploy to : ${APP_DOMAIN}\""
    - source /etc/.env && docker-compose up -d
  environment:
    name: rec
    url: http://${CI_PROJECT_PATH_SLUG}.rec.${BASE_DOMAIN}
  when: manual
  only:
    - ^release.*
  tags:
    - rec

deploy-demo:
  stage: deploy
  variables:
    APP_DOMAIN: ${CI_PROJECT_PATH_SLUG}.demo.${BASE_DOMAIN}
    COMPOSE_PROJECT_NAME: '${CI_PROJECT_PATH_SLUG}_demo'
  script:
    - "echo \"Deploy to : ${APP_DOMAIN}\""
    - source /etc/.env && docker-compose up -d
  environment:
    name: demo
    url: http://${CI_PROJECT_PATH_SLUG}.demo.${BASE_DOMAIN}
  when: manual
  only:
    - ^release.*
  tags:
    - demo
