version: "3"

volumes:
  database:
  tmp:

services:
  php:
    user: root
    command: "php-fpm -R"
    environment:
      PHP_FPM_USER: root
      PHP_FPM_GROUP: root
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_HOST: "192.168.56.10"
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /tmp/xdebug/profiler
      PHP_XDEBUG_TRACE_OUTPUT_DIR: /tmp/xdebug/traces
      PHP_BLACKFIRE: 1
    volumes:
      - ./:/var/www/html
      - tmp:/tmp:delegated
    ports:
      - 9001:9000

  apache:
    volumes:
      - ./:/var/www/html

  mariadb:
    volumes:
      - database:/var/lib/mysql:delegated
