version: "3"

networks:
  front:
    external:
      name: ${FRONT_NETWORK}
  back:
    driver: bridge

services:

  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - back

  php:
    image: wodby/drupal-php:7.1-3.0.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      COMPOSER_HOME: /tmp
      HOME: /tmp
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
    networks:
      - back
#  npm:
#    image: wodby/node
#    volumes_from:
#      - php
#    user: www-data
#    command: npm install
#
#  gulp:
#    image: wodby/node
#    volumes_from:
#      - php
#    depends_on:
#      - npm
#    user: www-data
#    working_dir: /var/www/html/web/sites/all/themes
#    command: gulp watch

  apache:
    image: wodby/php-apache:2.4-2.0.0
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html/web
      APACHE_SERVER_NAME: ${PROJECT_NAME}.${BASE_DOMAIN}
    networks:
      - front
      - back
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:origin.${PROJECT_NAME}.${BASE_DOMAIN}"

  varnish:
    image: wodby/drupal-varnish:4.1-2.2.0
    depends_on:
      - apache
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: apache
      VARNISH_BACKEND_PORT: 80
    networks:
      - front
    labels:
      - "traefik.enable=true"
      - "traefik.port=6081"
      - "traefik.frontend.rule=Host:${PROJECT_NAME}.${BASE_DOMAIN}"

  redis:
    image: wodby/redis:4.0-2.1.3
    networks:
      - back
  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    networks:
      - front
      - back
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.frontend.rule=Host:pma.${PROJECT_NAME}.${BASE_DOMAIN}"

  mailhog:
    image: mailhog/mailhog
    networks:
      - front
      - back
    labels:
      - "traefik.enable=true"
      - "traefik.port=8025"
      - "traefik.frontend.rule=Host:mailhog.${PROJECT_NAME}.${BASE_DOMAIN}"
