version: "3"

networks:
  front:
    external:
      name: ${FRONT_NETWORK}
  back:
    driver: bridge

services:
  php:
    volumes:
      - ./:/var/www/html:cached

  apache:
    volumes:
      - ./:/var/www/html:cached
