version: "3"

volumes:
  database:
  tmp:

services:
  php:
    environment:
      PHP_XDEBUG: 0
      PHP_XDEBUG_DEFAULT_ENABLE: 0
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_IDE_CONFIG: serverName=${APP_DOMAIN}
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /tmp/xdebug/profiler
      PHP_XDEBUG_TRACE_OUTPUT_DIR: /tmp/xdebug/traces
      PHP_BLACKFIRE: 0
      PHP_MAX_EXECUTION_TIME: 0
      APP_MODE: dev
    volumes:
      - ./:/var/www/html:cached
      - tmp:/tmp:delegated

  apache:
    volumes:
      - ./:/var/www/html:cached

  mariadb:
    volumes:
      - database:/var/lib/mysql:delegated
