version: "3"

volumes:
  docker-sync:
    external: true
  database:
  composer-cache:

services:
  php:
    volumes:
      #- ./:/var/www/html:cached
      - docker-sync:/var/www/html:nocopy
      - composer-cache:/tmp/cache:delegated

  apache:
    volumes:
      - docker-sync:/var/www/html:nocopy

  mariadb:
    volumes:
      - database:/var/lib/mysql:delegated
