version: "3"

volumes:
  docker-sync:
    external: true
  database:
  tmp:

services:
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_HOST: "0.0.0.0"
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /tmp/xdebug/profiler
      PHP_XDEBUG_TRACE_OUTPUT_DIR: /tmp/xdebug/traces
      PHP_BLACKFIRE: 1
    volumes:
      - docker-sync:/var/www/html:nocopy
      - tmp:/tmp:delegated
  apache:
    volumes:
      - docker-sync:/var/www/html:nocopy

  mariadb:
    volumes:
      - database:/var/lib/mysql:delegated
