version: "3"

networks:
  front:
    external:
      name: ${FRONT_NETWORK}
  back:
    driver: bridge

services:

  mariadb:
    container_name: ${COMPOSE_PROJECT_NAME}_mariadb
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - back
    healthcheck:
      test: "mysql --user=root --password=${MYSQL_ROOT_PASSWORD} --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 5

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    image: wodby/drupal-php:7.2-4.5.1
    depends_on:
      - mariadb
      - redis
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      COMPOSER_HOME: /tmp
      HOME: /tmp
      DB_HOST: ${MYSQL_HOST}
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      APP_MODE: ${APP_MODE}
      APP_HASH_SALT: ${APP_HASH_SALT}
    networks:
      - back

  apache:
    container_name: ${COMPOSE_PROJECT_NAME}_apache
    image: wodby/php-apache:2.4-3.0.5
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: ${COMPOSE_PROJECT_NAME}_php
      APACHE_SERVER_ROOT: /var/www/html/web
      APACHE_SERVER_NAME: ${APP_DOMAIN}
    networks:
      - front
      - back
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:origin.${APP_DOMAIN}"
      traefik.docker.network: "${FRONT_NETWORK}"

  varnish:
    container_name: ${COMPOSE_PROJECT_NAME}_varnish
    image: wodby/drupal-varnish:4.1-2.2.0
    depends_on:
      - apache
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: ${COMPOSE_PROJECT_NAME}_apache
      VARNISH_BACKEND_PORT: 80
    networks:
      - front
    labels:
      traefik.enable: "true"
      traefik.port: "6081"
      traefik.frontend.rule: "Host:${APP_DOMAIN}"
      traefik.docker.network: "${FRONT_NETWORK}"

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    image: wodby/redis:4.0-2.1.3
    networks:
      - back
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 3s
      timeout: 1s
      retries: 5

  pma:
    container_name: ${COMPOSE_PROJECT_NAME}_pma
    image: phpmyadmin/phpmyadmin:4.7.7-1
    environment:
      PMA_HOST: ${COMPOSE_PROJECT_NAME}_mariadb
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    networks:
      - front
      - back
    labels:
      traefik.enable: "true"
      traefik.port: "80"
      traefik.frontend.rule: "Host:pma.${APP_DOMAIN}"
      traefik.docker.network: "${FRONT_NETWORK}"

  mailhog:
    container_name: ${COMPOSE_PROJECT_NAME}_mailhog
    image: mailhog/mailhog:v1.0.0
    networks:
      - front
      - back
    labels:
      traefik.enable: "true"
      traefik.port: "8025"
      traefik.frontend.rule: "Host:mailhog.${APP_DOMAIN}"
      traefik.docker.network: "${FRONT_NETWORK}"
