#!/bin/bash

set -e

cd "$( dirname "${BASH_SOURCE[0]}" )"

EXEC_USER_ID=$(id -u)
EXEC_GROUP_ID=$(id -g)

source .env

nohup docker-sync start > /dev/null 2>&1 &

docker-compose -f docker-compose.yml -f docker-compose-dev.yml up -d

docker-compose exec php ./automation/bin/build.sh --mode dev

set +e
docker-compose exec php composer prepare-settings
set -e

docker-compose exec php ./automation/bin/install.sh
