steps:
  - id: copy-artifact
    name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://${_GCLOUD_ARTIFACTS_BUCKET}/${_CI_COMMIT_REF_SLUG}-${_CI_COMMIT_SHA}.tar.gz', '/workspace/artifact.tar.gz']

  - id: pull-for-cache
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker pull eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-latest || exit 0']

  - id: build-image
    name: gcr.io/cloud-builders/docker
    args: ['build',
           '--build-arg', 'PHP_VERSION=${_PHP_VERSION}',
           '--cache-from', 'eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-latest',
           '-t', 'eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-latest',
           '-t', 'eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-${_CI_COMMIT_SHA}',
           '-f', './automation/docker/DockerfilePHP',
           '.']

  - id: push-image-latest
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-latest']

  - id: push-image
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-${_CI_COMMIT_SHA}']

  - id: export-image
    name: gcr.io/cloud-builders/docker
    args: ['save',
            '-o', '${_CI_COMMIT_REF_SLUG}-${_CI_COMMIT_SHA}.php.docker.tar.gz',
            'eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-${_CI_COMMIT_SHA}']

artifacts:
  objects:
    location: 'gs://${_GCLOUD_ARTIFACTS_BUCKET}'
    paths: ['${_CI_COMMIT_REF_SLUG}-${_CI_COMMIT_SHA}.php.docker.tar.gz']

images:
  - 'eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-latest'
  - 'eu.gcr.io/${_GCLOUD_PROJECT_ID}/img/php:${_CI_COMMIT_REF_SLUG}-${_CI_COMMIT_SHA}'
