module:
  admin_toolbar: 0
  adminimal_admin_toolbar: 0
  block: 0
  breakpoint: 0
  config: 0
  config_filter: 0
  dynamic_page_cache: 0
  field: 0
  file: 0
  filter: 0
  help: 0
  language: 0
  locale: 0
  page_cache: 0
  redis: 0
  system: 0
  text: 0
  toolbar: 0
  user: 0
  views: 10
  niji: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
profile: niji
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
langcode: fr
